### ISSUE TITLE
support outputting binary circuit files

### ISSUE THREAD

**Issue by wangxiao1254** [emp-toolkit/emp-tool#40]
This is important for large circuits.

**Comment by weikengchen** [comment]
Will it also be meaningful to automatically find parallel execution paths in circuits (and prespecified in the file)?

i.e., if in the middle of an execution, the program is computing 1000 parallel AES, then the evaluation should be distributed to multiple cores. 

In traditional computing, the parallelism is unstable because accesses to shared resources are unpredictable. However, in a circuit, the computation is predictable and the parallel execution paths can be precomputed during the circuit outputting.

**Comment by wangxiao1254** [comment]
Great idea.

It is hard to define what is the best parallel strategy without giving the protocol and network setting. But I guess it can be done heuristically. All needed to be done is to extend the syntax of circuit files to allow annotation of parallel execution.

**Comment by wangxiao1254** [comment]
there is basically a practice to support it as in #121 now.
