### ISSUE TITLE
Source of Randomness: random_device

### ISSUE THREAD

**Issue by WeiViming** [emp-toolkit/emp-tool#81]
When I `cmake` the project, I get this message:
```
-- Build type: Release
-- CXX Flags: -pthread -Wall -march=native -O3 -maes -mrdseed -std=c++11
-- Source of Randomness: random_device
-- GMP libs: /usr/lib/x86_64-linux-gnu/libgmp.so /usr/lib/x86_64-linux-gnu/libgmpxx.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rean/Desktop/emp/emp-tool
```
I am confuse about the `Source of Randomness: random_device` is red color, why? Is something wrong with my device??But the compile works well.

**Comment by dymil** [comment]
Random guy here. The alternative is using `RDSEED` to seed the PRG, which would be in green text (because `std::random_device` _could_ be a PRNG with some compilers). Take a look at [source_of_randomness.cmake](https://github.com/emp-toolkit/emp-tool/blob/master/cmake/source_of_randomness.cmake). Perhaps your system doesn't support `RDSEED` or the relevant intrinsic isn't located in `<x86intrin.h>`? What compiler and processor are you using?

**Comment by WeiViming** [comment]
Oh, yes. My drive is old. The processor is `Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz`. Maybe I need to update my drive :) Thank you for your time. @dymil

**Comment by wangxiao1254** [comment]
My understanding is that random_device will make the best possible effort to use /dev/urand. However, it is much slower than rdseed. The difference is tiny if not invoked frequently.
